routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['web', 'auth', 'roles']],function(){
  Route::resource('home', 'HomeController');
  Route::group(['roles'=>'Author'],function(){
    //Route::resource('home', 'HomeController');
    Route::resource('blog', 'BlogController');
 });

  Route::group(['roles'=>'Admin'],function(){
    //Route::resource('home', 'HomeController');
    Route::resource('pageblog', 'PageBlogController');
    Route::resource('user', 'UserController');
 });
});

resources/views/home.blade.php
@extends('layouts.app')
@section('pageTitle', 'Dashboard')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <?php if (Auth::user()->role_id == 1): ?>
                        <div class="col-md-12">
                          <div class="jumbotron">
                            <center>
                              <h1>Welcome</h1>
                              <p>You are login as <b>Admin</b></p>
                              <p>
                                <a class="btn btn-default btn-primary" href="{{ url('pageblog') }}" role="button"> View Blog </a>
                                <a class="btn btn-default btn-success" href="{{ route('user.create') }}" role="button"> create User </a>
                              </p>
                            </center>
                          </div>
                        </div>

                    <?php else: ?>
                      <div class="col-md-12">
                        <div class="jumbotron">
                          <center>
                            <h1>Welcome</h1>
                            <p>You are login as <b>Author</b></p>
                            <p>
                              <a class="btn btn-default btn-primary" href="{{ url('blog') }}" role="button"> View Blog </a>
                            </p>
                          </center>
                        </div>
                      </div>
                    <?php endif; ?>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection