routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['web', 'auth', 'roles']],function(){
  Route::resource('home', 'HomeController');
  Route::group(['roles'=>'Author'],function(){
    //Route::resource('home', 'HomeController');
    Route::resource('blog', 'BlogController');
 });

  Route::group(['roles'=>'Admin'],function(){
    //Route::resource('home', 'HomeController');
    Route::resource('pageblog', 'PageBlogController');
    Route::resource('user', 'UserController');
 });
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
  // Digunakan untuk menggunakan soft delete secara default saat menghapus data
//  use SoftDeletes;

    protected $fillable = [
        'title', 'content'
    ];
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blog;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $blogs = Blog::orderBy('id', 'ASC')->paginate(5);
      return view('blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'title' => 'required',
          'content' => 'required'
      ]);

      $blog = Blog::create($request->all());

      return redirect()->route('blog.index')->with('message', 'Artikel berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $blog = Blog::findOrFail($id);
      return view('blog.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
     {
         $blog = Blog::findOrFail($id);
         return view('blog.edit', compact('blog'));
     }

     /**
      * Update the specified resource in storage.
      *
      * @param  \Illuminate\Http\Request  $request
      * @param  int  $id
      * @return \Illuminate\Http\Response
      */
     public function update(Request $request, $id)
     {
         $this->validate($request, [
             'title' => 'required',
             'content' => 'required'
         ]);

         $blog = Blog::findOrFail($id)->update($request->all());

         return redirect()->route('blog.index')->with('message', 'Artikel berhasil diubah!');
     }

     /**
      * Remove the specified resource from storage.
      *
      * @param  int  $id
      * @return \Illuminate\Http\Response
      */
     public function destroy($id)
     {
         $blog = Blog::findOrFail($id)->delete();
         return redirect()->route('blog.index')->with('message', 'Artikel berhasil dihapus!');
     }
}

resources/views/blog/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Artikel</div>

                <div class="card-body">
                  <h4>Artikel Baru</h4>
                  <form action="{{ route('blog.store') }}" method="post">
                      {{csrf_field()}}
                      <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                          <label for="title" class="control-label">Title</label>
                          <input type="text" class="form-control" name="title" placeholder="Title">
                          @if ($errors->has('title'))
                              <span class="help-block">{{ $errors->first('title') }}</span>
                          @endif
                      </div>
                      <div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}">
                          <label for="content" class="control-label">Content</label>
                          <textarea name="content" cols="30" rows="5" class="form-control"></textarea>
                          @if ($errors->has('content'))
                              <span class="help-block">{{ $errors->first('content') }}</span>
                          @endif
                      </div>
                      <div class="form-group">
                          <button type="submit" class="btn btn-info">Simpan</button>
                          <a href="{{ route('blog.index') }}" class="btn btn-default">Kembali</a>
                      </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Artikel</div>

                <div class="card-body">
                  <h4>Ubah Artikel</h4>
                  <form action="{{ route('blog.update', $blog->id) }}" method="post">
                      {{csrf_field()}}
                      {{ method_field('PUT') }}
                      <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                          <label for="title" class="control-label">Title</label>
                          <input type="text" class="form-control" name="title" placeholder="Title" value="{{ $blog->title }}">
                          @if ($errors->has('title'))
                              <span class="help-block">{{ $errors->first('title') }}</span>
                          @endif
                      </div>
                      <div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}">
                          <label for="content" class="control-label">Content</label>
                          <textarea name="content" cols="30" rows="5" class="form-control">{{ $blog->content }}</textarea>
                          @if ($errors->has('content'))
                              <span class="help-block">{{ $errors->first('content') }}</span>
                          @endif
                      </div>
                      <div class="form-group">
                          <button type="submit" class="btn btn-info">Simpan</button>
                          <a href="{{ route('blog.index') }}" class="btn btn-default">Kembali</a>
                      </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Artikel</div>

                <div class="card-body">
                  <a href="{{ route('blog.create') }}" class="btn btn-primary">Artikel Baru</a>
                  <br><br>

                  @if ($message = Session::get('message'))
                      <div class="alert alert-success martop-sm">
                          <p>{{ $message }}</p>
                      </div>
                  @endif
                    <table class="table table-hover border">
                      <thead style="background:#a8c6f7">
                          <th>ID</th>
                          <th style="width:70%">Title</th>
                          <th>Action</th>
                      </thead>
                      <tbody>
                          {{-- buat nomor urut --}}
                          @php($no = 1)
                          {{-- loop all --}}
                          @foreach ($blogs as $blog)
                              <tr>
                                  <td>{{ $no++ }}</td>
                                  <td>{{ $blog->title }}</td>
                                  <td>
                                      <form action="{{ route('blog.destroy', $blog->id) }}" method="post">
                                          {{csrf_field()}}
                                          {{ method_field('DELETE') }}
                                          <a href="{{ route('blog.show', $blog->id) }}" class="btn btn-success btn-sm">View</a>
                                          <a href="{{ route('blog.edit', $blog->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                                          <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                                      </form>
                                  </td>
                              </tr>
                          @endforeach
                          {{-- // end loop --}}
                      </tbody>
                  </table>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/blog/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Artikel</div>

                <div class="card-body">
                  <h4>{{ $blog->title }}</h4>
                  <p>{{ $blog->content }}</p>
                  <a href="{{ route('blog.index') }}" class="btn btn-default">Kembali</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection